/usr/src/tensorrt/bin/trtexec \
        --onnx=./work_dirs/rtmdet/end2end.onnx \
        --saveEngine=./work_dirs/rtmdet/end2end_trtexec_fp32_opt.plan \
        --workspace=100000000 \
        --buildOnly \
        --noTF32 \
        --useDLACore=0 \
        --allowGPUFallback \
        --verbose \